### ISSUE TITLE
No image upload

### ISSUE THREAD

**Issue by JLKM** [yyss8/Scms#3]
Having further developed your blog into a CMS with categories, tags, seo-friendly urls and more fields I've bumped into what seems to be one last hurdle:
Images won't upload. Have tested both .png and .jpg - and on both Windows and Ubuntu but same result.
The image name is displayed, and it's also possible to preview it. But a click in the red Upload-button seems to initiate nothing. And after save, nothing has happened.
Please don't bother, if it's not supposed to work. Then i'll manage without.

**Comment by yyss8** [comment]
Hi, JLKM 
I didn't develop the image upload feature and that's the place that I stopped developing the app, because I was stuck at trying to have the server side returning the upload percentage. 

I tried to pick it up a couple months later, but then I found it to be very hard to continue without remembering the meaning of those variable and the previous logic

So, feel free to rewrite entire component, because it basically doesn't have any functionality in that component

**Comment by JLKM** [comment]
A straight answer is always preferable. Even if it is not exactly the answer hoped for.
And thank you for the fast response.
I'll just eliminate the image-upload code and keep on refining the SSR MEVN stack.
